### ISSUE TITLE
Solutions

### ISSUE THREAD

**Issue by miles992** [AFLplusplus/fuzzer-challenges#2]
Is there a documentation about the expected solutions (aside from the solution time) also, are all results deterministic in any case? From what I see all the test cases are created in a way to just hit the abort() correct? So they mostly test the mutator capabilities to find the path, not the detection capabilities?
Is there any testcase which show the ability to detect certain bugs in the target instead of path finding capabilities?

**Comment by vanhauser-thc** [comment]
All are deterministic, they are not documented.

**Comment by vanhauser-thc** [comment]
They do not test the mutator. They test the path constraint solving capabilities of a fuzzer. beside u8/u16 they can’t be solved with mutation

**Comment by miles992** [comment]
Thanks for the info!
